### ISSUE TITLE
Share contact info

### ISSUE THREAD

**Issue by 1t5j0y** [1t5j0y/lmi-pwa#1]
# Story
As a social person / business
I want to share my contact info
so that new acquaintances / customers can keep in touch with me.

# Acceptance Criteria
- [ ] User can add their contact info manually
    - [ ] phone numbers
    - [ ] social media urls (FB, Insta, LinkedIn, Twitter)
    - [ ] address
    - [ ] location
- [ ] User can generate QR codes for other users to scan
