### ISSUE TITLE
Grab Contact info

### ISSUE THREAD

**Issue by 1t5j0y** [1t5j0y/lmi-pwa#2]
## Story
As a new acquaintance / customer
I want to view and save the person / business' contact info
so that I can follow them and keep in touch

## Acceptance Criteria
- [ ] Scan QR code (in external app)
- [ ] View contact info
- [ ] Save contact info
